version: '3.9'

services:
  fastapi:
    build: .
    command: gunicorn server:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    environment:
      - ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}

  streamlit:
    build: .
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    restart: always
    env_file:
      - .env
    environment:
      - ENV=production
      - GROQ_API_KEY=${GROQ_API_KEY}
