name: Docker CI/CD to EC2

on:
  push:
    branches: [main]  # or 'master', if that's your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE }} .
        docker push ${{ secrets.DOCKER_IMAGE }}

    - name: Deploy to EC2 and restart container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 30m
        script: |
          docker pull ${{ secrets.DOCKER_IMAGE }}
          docker stop cascadelog || true
          docker rm cascadelog || true
          docker run -d --name cascadelog \
            -p 8000:8000 \
            -p 8501:8501 \
            --env-file .env \
            -v /home/ubuntu/CascadeLog/resources:/app/resources \
            --restart unless-stopped \
            ${{ secrets.DOCKER_IMAGE }}
